import { Funnel_Display, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const funnel = Funnel_Display({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  variable: "--font-funnel",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${funnel.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" style={{ fontFamily: 'var(--font-funnel)' }}>
        {children}
      </body>
    </html>
  );
}